# Generated by Django 4.2.7 on 2023-11-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="clay_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="project",
            name="glaze_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="project",
            name="needle_size",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="project",
            name="object_type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="project",
            name="yarn_amount",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="project",
            name="yarn_weight",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
